Traceback (most recent call last):
  File "C:/Users/ssel512/PycharmProjects/Finally_Research/0829/1.GA&Labeling_hyper-parameter_20171109-20220401/1---GA_based_labeling.py", line 241, in <module>
    model.training()
  File "C:/Users/ssel512/PycharmProjects/Finally_Research/0829/1.GA&Labeling_hyper-parameter_20171109-20220401/1---GA_based_labeling.py", line 146, in training
    self.optimizer = GA.BaseGA(self.problem, GAepoch=self.GA_epoch,pop_size=self.pop_size, pc=0.7, pm=0.4)
  File "D:\anaconda3\envs\torchGpu\lib\site-packages\mealpy\evolutionary_based\GA.py", line 84, in __init__
    self.epoch = self.validator.check_int("epoch", epoch, [1, 100000])
  File "D:\anaconda3\envs\torchGpu\lib\site-packages\mealpy\utils\validator.py", line 54, in check_int
    raise ValueError(f"'{name}' is an integer {bound}.")
ValueError: 'epoch' is an integer and value should be in range: [1, 100000].
Traceback (most recent call last):
  File "C:/Users/ssel512/PycharmProjects/research0902/HRHP/1.GA&Labeling_hyper-parameter_20171109-20220401/1---GA_based_labeling.py", line 239, in <module>
    model = HybridMlp(tests,pair_train,GA_epoch,GA_pop_size) #dataset,
TypeError: __init__() takes 4 positional arguments but 5 were given
Traceback (most recent call last):
  File "C:/Users/ssel512/PycharmProjects/research0902/HRHP/1.GA&Labeling_hyper-parameter_20171109-20220401/1---GA_based_labeling.py", line 241, in <module>
    model.training()
  File "C:/Users/ssel512/PycharmProjects/research0902/HRHP/1.GA&Labeling_hyper-parameter_20171109-20220401/1---GA_based_labeling.py", line 146, in training
    self.optimizer = GA.BaseGA(self.problem, GAepoch=self.GA_epoch,pop_size=self.pop_size, pc=0.7, pm=0.4)
  File "D:\anaconda3\envs\algTrading\lib\site-packages\mealpy\evolutionary_based\GA.py", line 80, in __init__
    self.epoch = self.validator.check_int("epoch", epoch, [1, 100000])
  File "D:\anaconda3\envs\algTrading\lib\site-packages\mealpy\utils\validator.py", line 54, in check_int
    raise ValueError(f"'{name}' is an integer {bound}.")
ValueError: 'epoch' is an integer and value should be in range: [1, 100000].
Traceback (most recent call last):
  File "C:/Users/ssel512/PycharmProjects/research0902/HRHP/1.GA&Labeling_hyper-parameter_20171109-20220401/1---GA_based_labeling.py", line 241, in <module>
    model.training()
  File "C:/Users/ssel512/PycharmProjects/research0902/HRHP/1.GA&Labeling_hyper-parameter_20171109-20220401/1---GA_based_labeling.py", line 147, in training
    self.solution, self.best_fit = self.optimizer.solve(self.problem)
  File "D:\anaconda3\envs\algTrading\lib\site-packages\mealpy\optimizer.py", line 223, in solve
    self.check_problem(problem, seed)
  File "D:\anaconda3\envs\algTrading\lib\site-packages\mealpy\optimizer.py", line 157, in check_problem
    self.problem = Problem(**problem)
TypeError: __init__() missing 1 required positional argument: 'bounds'
Traceback (most recent call last):
  File "C:/Users/ssel512/PycharmProjects/research0902/HRHP/1.GA&Labeling_hyper-parameter_20171109-20220401/1---GA_based_labeling.py", line 242, in <module>
    model.training()
  File "C:/Users/ssel512/PycharmProjects/research0902/HRHP/1.GA&Labeling_hyper-parameter_20171109-20220401/1---GA_based_labeling.py", line 148, in training
    self.solution, self.best_fit = self.optimizer.solve(self.problem)
  File "D:\anaconda3\envs\algTrading\lib\site-packages\mealpy\optimizer.py", line 223, in solve
    self.check_problem(problem, seed)
  File "D:\anaconda3\envs\algTrading\lib\site-packages\mealpy\optimizer.py", line 157, in check_problem
    self.problem = Problem(**problem)
  File "D:\anaconda3\envs\algTrading\lib\site-packages\mealpy\utils\problem.py", line 28, in __init__
    self.__set_functions()
  File "D:\anaconda3\envs\algTrading\lib\site-packages\mealpy\utils\problem.py", line 65, in __set_functions
    result = self.obj_func(tested_solution)
  File "D:\anaconda3\envs\algTrading\lib\site-packages\mealpy\utils\problem.py", line 97, in obj_func
    raise NotImplementedError
NotImplementedError
Traceback (most recent call last):
  File "C:/Users/ssel512/PycharmProjects/research0902/HRHP/1.GA&Labeling_hyper-parameter_20171109-20220401/1---GA_based_labeling.py", line 242, in <module>
    model.training()
  File "C:/Users/ssel512/PycharmProjects/research0902/HRHP/1.GA&Labeling_hyper-parameter_20171109-20220401/1---GA_based_labeling.py", line 148, in training
    self.solution, self.best_fit = self.optimizer.solve(self.problem)
AttributeError: 'HybridMlp' object has no attribute 'problem'
Traceback (most recent call last):
  File "C:/Users/ssel512/PycharmProjects/research0902/HRHP/1.GA&Labeling_hyper-parameter_20171109-20220401/1---GA_based_labeling.py", line 243, in <module>
    model.training()
  File "C:/Users/ssel512/PycharmProjects/research0902/HRHP/1.GA&Labeling_hyper-parameter_20171109-20220401/1---GA_based_labeling.py", line 149, in training
    self.solution, self.best_fit = self.optimizer.solve(self.create_problem())
  File "D:\anaconda3\envs\algTrading\lib\site-packages\mealpy\optimizer.py", line 223, in solve
    self.check_problem(problem, seed)
  File "D:\anaconda3\envs\algTrading\lib\site-packages\mealpy\optimizer.py", line 157, in check_problem
    self.problem = Problem(**problem)
  File "D:\anaconda3\envs\algTrading\lib\site-packages\mealpy\utils\problem.py", line 28, in __init__
    self.__set_functions()
  File "D:\anaconda3\envs\algTrading\lib\site-packages\mealpy\utils\problem.py", line 65, in __set_functions
    result = self.obj_func(tested_solution)
  File "D:\anaconda3\envs\algTrading\lib\site-packages\mealpy\utils\problem.py", line 97, in obj_func
    raise NotImplementedError
NotImplementedError
Traceback (most recent call last):
  File "C:/Users/ssel512/PycharmProjects/research0902/HRHP/1.GA&Labeling_hyper-parameter_20171109-20220401/1---GA_based_labeling.py", line 243, in <module>
    model.training()
  File "C:/Users/ssel512/PycharmProjects/research0902/HRHP/1.GA&Labeling_hyper-parameter_20171109-20220401/1---GA_based_labeling.py", line 149, in training
    self.solution, self.best_fit = self.optimizer.solve(self.problem)
AttributeError: 'HybridMlp' object has no attribute 'problem'
Traceback (most recent call last):
  File "C:/Users/ssel512/PycharmProjects/research0902/HRHP/1.GA&Labeling_hyper-parameter_20171109-20220401/test_1207.py", line 239, in <module>
    model = HybridMlp(tests,pair_train,GA_epoch,GA_pop_size) #dataset,
TypeError: __init__() takes 4 positional arguments but 5 were given
Traceback (most recent call last):
  File "C:/Users/ssel512/PycharmProjects/research0902/HRHP/1.GA&Labeling_hyper-parameter_20171109-20220401/test_1207.py", line 241, in <module>
    model.training()
  File "C:/Users/ssel512/PycharmProjects/research0902/HRHP/1.GA&Labeling_hyper-parameter_20171109-20220401/test_1207.py", line 146, in training
    self.optimizer = GA.BaseGA(self.problem, GAepoch=self.GA_epoch,pop_size=self.pop_size, pc=0.7, pm=0.4)
  File "D:\anaconda3\envs\algTrading\lib\site-packages\mealpy\evolutionary_based\GA.py", line 80, in __init__
    self.epoch = self.validator.check_int("epoch", epoch, [1, 100000])
  File "D:\anaconda3\envs\algTrading\lib\site-packages\mealpy\utils\validator.py", line 54, in check_int
    raise ValueError(f"'{name}' is an integer {bound}.")
ValueError: 'epoch' is an integer and value should be in range: [1, 100000].
Traceback (most recent call last):
  File "C:/Users/ssel512/PycharmProjects/research0902/HRHP/1.GA&Labeling_hyper-parameter_20171109-20220401/test_1207.py", line 241, in <module>
    model.training()
  File "C:/Users/ssel512/PycharmProjects/research0902/HRHP/1.GA&Labeling_hyper-parameter_20171109-20220401/test_1207.py", line 147, in training
    self.solution, self.best_fit = self.optimizer.solve(self.problem)
  File "D:\anaconda3\envs\algTrading\lib\site-packages\mealpy\optimizer.py", line 223, in solve
    self.check_problem(problem, seed)
  File "D:\anaconda3\envs\algTrading\lib\site-packages\mealpy\optimizer.py", line 157, in check_problem
    self.problem = Problem(**problem)
TypeError: __init__() missing 1 required positional argument: 'bounds'
Traceback (most recent call last):
  File "C:/Users/ssel512/PycharmProjects/research0902/HRHP/1.GA&Labeling_hyper-parameter_20171109-20220401/test_1207.py", line 241, in <module>
    model.training()
  File "C:/Users/ssel512/PycharmProjects/research0902/HRHP/1.GA&Labeling_hyper-parameter_20171109-20220401/test_1207.py", line 147, in training
    self.solution, self.best_fit = self.model.solve(self.problem)
  File "D:\anaconda3\envs\algTrading\lib\site-packages\mealpy\optimizer.py", line 223, in solve
    self.check_problem(problem, seed)
  File "D:\anaconda3\envs\algTrading\lib\site-packages\mealpy\optimizer.py", line 157, in check_problem
    self.problem = Problem(**problem)
TypeError: __init__() missing 1 required positional argument: 'bounds'
